### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by mangerlahn**
This pull request converts the code base to Swift 3. It is not ready for merging yet, as the deployment target was raised to 10.12 (from 10.9) for convenience. We should set that back somehow.

### CODE REVIEW

**Comment by toricls** [comment]
Thanks for the pull request. I'll take a look into it.

**Comment by toricls** [comment]
I think we don't have to support old macOS (or 'OS X'?). so I'll merge this PR after inspecting & fixing problems on CI.
Do you mind if I add some commits to this PR to fix that?

**Comment by mangerlahn** [comment]
I'm sorry! I've missed the notification that you answered. I am happy to contribute some fixes.

**Comment by toricls** [comment]
@mangerlahn It's finally merged into master by #4. Thanks for your contribution!

**Pull request merged**
